#!/bin/bash
echo " "
echo " Hu Z is a sb "
echo "         --Albert Einstein"
echo " "
#MING has travelde here.
read -p '  If Hu Z is a sb?(Please input "yes" or "no" )     ' SB
if [ $SB = yes ] ; then
    while [ 8890 -gt 6950 ]
        do
            echo 'Yes!Hu Z is a sb!'
        done
elif [ $SB = no ] ; then
    while [ 2699 -lt  6950 ]
        do
            echo 'No!Hu Z is a sb!'
        done
else
    while [ 2699 -gt 1230 ]
        do
            echo '  Are you kidding me?   '
        done
fi