#!/system/bin/sh
clear
echo "__________________________________________"
echo "                                          "
echo "   MM      MM GGGGGGGGGGGGGG              "
echo "   MMM    MMM GGGGGGGGGGGGG               "
echo "   MMMM  MMMM                             "
echo "   MM MMMM MM                             "
echo "   MM  MM  MM     GGGGG                   "
echo "   MM      MM    GGGGGGG      MING        "
echo "   MM      MM         GGG                 "
echo "   MM      MM          GGG                "
echo "   MM      MM GGGGGGGGGGGGG               "
echo "   MM      MM GGGGGGGGGGGGGG              "
echo "                                          "
echo "                                          "
echo "  Hellow!It's MING's Android smart phone. "
echo "    The Linux is based on MIUI(#滑稽).    "
echo "       Android Bar @MING19980628          "
echo "__________________________________________"
echo " "
uname -a
echo Last login:`date`
cd ..
cd ..
echo $
echo $

