#!/system/bin/sh
clear
echo "__________________________________________"
echo "           ___         _"
echo "          |   |___ ___| |_"
echo "          | | | -_|  -|  _|"
echo "          |_|_|___|  _|___|"
echo "           NEPTUNE|_|LIANG"
echo "                                          "
echo "  Hellow!It's MING's Android smart phone. "
echo "    The Linux is based on MIUI(#滑稽).    "
echo "       Android Bar @MING19980628          "
echo "__________________________________________"
echo " "
uname -a
cd ..
echo $
echo $
