#!/bin/sh
echo U....URRRRRR......AAAA.........NNNNNN
echo U....U......R.....A...A........N     N
echo U....U.......R....A....A.......N      N
echo U....U......R.....A.....A      N       N
echo U....U.RRRRR......A......A     N       N
echo U ...U.R....R.....A.......A    N       N
echo U....U.R.....R....A........A   N       N
echo .U...U.R......R...AAAAAAAAAAA  N       N
echo ..U..U.R.......R..A..........A N       N
echo ...UUU.R........RRA...........AN       N